### ISSUE TITLE
Fix native npm builds

### ISSUE THREAD

**Issue by ArtskydJ** [ArtskydJ/-#10]
On my machine, npm builds are broken. This started when I installed MSVS 2015 for work. As I'm not planning to use MSVS 2015 for work anymore, I should be able to uninstall all versions of MSVS, and follow [these instructions](https://github.com/nodejs/node-gyp/issues/629#issuecomment-153196245). Or just uninstall 2015 and repair-install 2010 like [I did before](https://github.com/nodejs/node-gyp/issues/629#issuecomment-128465742). Or try the [python solution](https://github.com/nodejs/node-gyp/issues/629#issuecomment-128531553) that I don't yet understand.

**Comment by ArtskydJ** [comment]
Still broken. Should be more easily fixed now that I don't need MSVS 2015.

```
C:\Users\Michael\Github\JS_Source>npm i weak

> weak@1.0.1 install C:\Users\Michael\Github\JS_Source\node_modules\weak
> node-gyp rebuild


C:\Users\Michael\Github\JS_Source\node_modules\weak>if not defined npm_config_node_gyp (node "C:\Users\Michael\AppData\Roaming\nvm\v4.2.1\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
Project file contains ToolsVersion="14.0". This toolset may be unknown or missing, in which case you may be able to resolve this by installing the appropriate version of MSBuild, or the build may have been forced to a particular ToolsVersion for policy reasons. Treating the project as if it had ToolsVersion="4.0". For more information, please see http://go.microsoft.com/fwlink/?LinkId=291333.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.Cpp.InvalidPlatform.Targets(23,7): error MSB8007: The Platform for project 'weakref.vcxproj' is invalid.  Platform='x64'. You may be seeing this message because you are trying to build a project without a solution file, and have specified a non-default Platform that doesn't exist for this project. [C:\Users\Michael\Github\JS_Source\node_modules\weak\build\weakref.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Michael\AppData\Roaming\nvm\v4.2.1\node_modules\npm\node_modules\node-gyp\lib\build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Michael\\AppData\\Roaming\\nvm\\v4.2.1\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Michael\Github\JS_Source\node_modules\weak
gyp ERR! node -v v4.2.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm WARN EPACKAGEJSON JS_Source@1.0.0 No description
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "weak"
npm ERR! node v4.2.1
npm ERR! npm  v3.3.8
npm ERR! code ELIFECYCLE

npm ERR! weak@1.0.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the weak@1.0.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the weak package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls weak
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Michael\Github\JS_Source\npm-debug.log

C:\Users\Michael\Github\JS_Source>
```

**Comment by ArtskydJ** [comment]
In progress...

I am attempting the Microsoft Visual C++ Build Tools 2015 Technical Preview method described [here](https://github.com/nodejs/node-gyp/issues/629#issuecomment-153196245).

**Comment by ArtskydJ** [comment]
Ate up 7gb, but it worked!
